#!/bin/bash

set -e


help() {
    echo "usage: dredis-snapshot [-h] [-d] [-x] <dredis-host> <dredis-port> [<local-path> | <s3-path>]"
    echo
    echo "-h: Display this message"
    echo "-d: Enable debug mode"
    echo "-x: Delete snapshot directory after creating tarball (save disk space after copying snapshot to <local-path> or <s3-path>)"
    echo
    echo "examples:"
    echo "  dredis-snapshot -d 127.0.0.1 6377 s3://dredis-snapshots"
    echo "  dredis-snapshot 127.0.0.1 6377"
    echo "  dredis-snapshot 127.0.0.1 6377 /tmp/dredis-snapshot-2018.tar.gz"
    echo "  dredis-snapshot 127.0.0.1 6377 s3://dredis-snapshots/dredis-snapshot-2018.tar.gz"
    exit 1
}


debug() {
    msg="$1"
    test ! -z "$debug_mode" && echo [DEBUG] $msg || true
}


main() {
    debug "Snapshotting dredis..."
    snapshot_dir="$(redis-cli -h $dredis_host -p $dredis_port save)"
    debug "Redis snapshot created at $snapshot_dir"

    debug "Creating $tarball_name..."
    tar -C "$(dirname $snapshot_dir)" -czf "$tarball_name" "$(basename $snapshot_dir)"

    if [[ ! -z $delete_snapshot ]]; then
        debug "Deleting snapshot after tarball ($snapshot_dir)"
        rm -rf $snapshot_dir
    fi


    if [[ -z "$s3_path" ]]; then
        echo "Snapshot: $tarball_name"
    else
        debug "Uploading to $s3_path..."
        aws s3 cp "$tarball_name" "$s3_path"

        debug "Removing $tarball_name"
        rm "$tarball_name"
    fi
}


default_tarball_name="dredis-snapshot-$(date +\%Y-\%m-\%dT\%H-\%M-\%S).tar.gz"

if [[ "$1" = "-h" ]] ; then
    help
fi

if [[ "$1" = "-d" ]]; then
    debug_mode="-d"
    shift
fi
if [[ "$1" = "-x" ]]; then
    delete_snapshot="-x"
    shift
fi

dredis_host="$1"
shift
dredis_port="$1"
shift

test -z "$dredis_host" && help
test -z "$dredis_port" && help

if [[ "$1" == s3://* ]]; then
    tarball_name="$default_tarball_name"
    s3_path="$1"
else
    tarball_name="${1:-$default_tarball_name}"
fi

main
